# Makefile.Vx
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

USR_INCLUDES += -I$(SHARE)/camacApp/src

LIBNAME = devCamacLib

SRCS.c += ../devCamac.c  ../devScalerCamac.c ../devMotorE500.c ../drvMotorE500.c

LIBOBJS += devCamac.o  devScalerCamac.o devMotorE500.o drvMotorE500.o


include $(TOP)/config/RULES.Vx
#----------------------------------------
#  ADD RULES AFTER THIS LINE
inc:: $(INSTALL_INCREC)
